/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jme3_util_AndroidNativeBufferAllocator */

#ifndef _Included_com_jme3_util_AndroidNativeBufferAllocator
#define _Included_com_jme3_util_AndroidNativeBufferAllocator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jme3_util_AndroidNativeBufferAllocator
 * Method:    releaseDirectByteBuffer
 * Signature: (Ljava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_util_AndroidNativeBufferAllocator_releaseDirectByteBuffer
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_jme3_util_AndroidNativeBufferAllocator
 * Method:    createDirectByteBuffer
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_jme3_util_AndroidNativeBufferAllocator_createDirectByteBuffer
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
