/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jme3_texture_plugins_AndroidNativeImageLoader */

#ifndef _Included_com_jme3_texture_plugins_AndroidNativeImageLoader
#define _Included_com_jme3_texture_plugins_AndroidNativeImageLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jme3_texture_plugins_AndroidNativeImageLoader
 * Method:    load
 * Signature: (Ljava/io/InputStream;Z[B)Lcom/jme3/texture/Image;
 */
JNIEXPORT jobject JNICALL Java_com_jme3_texture_plugins_AndroidNativeImageLoader_load
  (JNIEnv *, jclass, jobject, jboolean, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
