/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jme3_audio_plugins_NativeVorbisFile */

#ifndef _Included_com_jme3_audio_plugins_NativeVorbisFile
#define _Included_com_jme3_audio_plugins_NativeVorbisFile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jme3_audio_plugins_NativeVorbisFile
 * Method:    seekTime
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_jme3_audio_plugins_NativeVorbisFile_seekTime
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_jme3_audio_plugins_NativeVorbisFile
 * Method:    readIntoArray
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_com_jme3_audio_plugins_NativeVorbisFile_readIntoArray
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     com_jme3_audio_plugins_NativeVorbisFile
 * Method:    readIntoBuffer
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_audio_plugins_NativeVorbisFile_readIntoBuffer
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_jme3_audio_plugins_NativeVorbisFile
 * Method:    clearResources
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jme3_audio_plugins_NativeVorbisFile_clearResources
  (JNIEnv *, jobject);

/*
 * Class:     com_jme3_audio_plugins_NativeVorbisFile
 * Method:    preInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jme3_audio_plugins_NativeVorbisFile_preInit
  (JNIEnv *, jclass);

/*
 * Class:     com_jme3_audio_plugins_NativeVorbisFile
 * Method:    init
 * Signature: (IJJ)V
 */
JNIEXPORT void JNICALL Java_com_jme3_audio_plugins_NativeVorbisFile_init
  (JNIEnv *, jobject, jint, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
